"""new user statistics table

Revision ID: 83a0489cfb58
Revises: b1d7c7ba953c
Create Date: 2023-07-17 11:40:23.635261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a0489cfb58'
down_revision = 'b1d7c7ba953c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersStats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_usersStats_post_count'), 'usersStats', ['post_count'], unique=False)
    op.create_index(op.f('ix_usersStats_user_id'), 'usersStats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersStats_user_id'), table_name='usersStats')
    op.drop_index(op.f('ix_usersStats_post_count'), table_name='usersStats')
    op.drop_table('usersStats')
    # ### end Alembic commands ###
